### ISSUE TITLE
Systemd .timer file is not working correctly

### ISSUE THREAD

**Issue by slaufmann** [grandchild/flatcrawler#15]
The systemd files that are created by the `install` command do not work correctly. As suggested on [serverfault.com](https://serverfault.com/questions/775246/systemd-timer-not-starting-its-service-unit) the `[Unit]` section of the flatcrawler.timer file misses:
```bash
Requires=flatcrawler.service
```

**Comment by grandchild** [comment]
I wanted to check this. Because it works for me. Might be dependent on the version of systemd.
